---
- name: Install and configure dotfiles
  hosts: localhost
  become: false
  vars:
    supported_distributions:
      - fedora
      - ubuntu
      - debian
      - arch

  pre_tasks:
    - name: Check Linux distribution
      ansible.builtin.assert:
        that: ansible_distribution | lower in supported_distributions
        fail_msg: "Unsupported distribution: {{ ansible_distribution }}"

  roles:
    - common
    - hypr
    - nvim
    - tmux
    - wezterm
    - zsh
